// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bets.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createBet = `-- name: CreateBet :one
INSERT INTO bets (round_id, player_id, amount, auto_cashout)
VALUES ($1, $2, $3, $4)
RETURNING id, round_id, player_id, amount, auto_cashout, cashed_out_at_multiplier, payout, created_at
`

type CreateBetParams struct {
	RoundID     int64
	PlayerID    int64
	Amount      int64
	AutoCashout sql.NullInt32
}

func (q *Queries) CreateBet(ctx context.Context, arg CreateBetParams) (Bet, error) {
	row := q.db.QueryRowContext(ctx, createBet,
		arg.RoundID,
		arg.PlayerID,
		arg.Amount,
		arg.AutoCashout,
	)
	var i Bet
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.PlayerID,
		&i.Amount,
		&i.AutoCashout,
		&i.CashedOutAtMultiplier,
		&i.Payout,
		&i.CreatedAt,
	)
	return i, err
}

const getBetsForRound = `-- name: GetBetsForRound :many
SELECT b.id, b.round_id, b.player_id, b.amount, b.auto_cashout, b.cashed_out_at_multiplier, b.payout, b.created_at, p.pubkey_fingerprint, p.display_name
FROM bets b
JOIN players p ON p.id = b.player_id
WHERE b.round_id = $1
`

type GetBetsForRoundRow struct {
	ID                    int64
	RoundID               int64
	PlayerID              int64
	Amount                int64
	AutoCashout           sql.NullInt32
	CashedOutAtMultiplier sql.NullInt32
	Payout                sql.NullInt64
	CreatedAt             time.Time
	PubkeyFingerprint     string
	DisplayName           string
}

func (q *Queries) GetBetsForRound(ctx context.Context, roundID int64) ([]GetBetsForRoundRow, error) {
	rows, err := q.db.QueryContext(ctx, getBetsForRound, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBetsForRoundRow{}
	for rows.Next() {
		var i GetBetsForRoundRow
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.PlayerID,
			&i.Amount,
			&i.AutoCashout,
			&i.CashedOutAtMultiplier,
			&i.Payout,
			&i.CreatedAt,
			&i.PubkeyFingerprint,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const settleBet = `-- name: SettleBet :one
UPDATE bets
SET cashed_out_at_multiplier = $2,
    payout = $3
WHERE id = $1
RETURNING id, round_id, player_id, amount, auto_cashout, cashed_out_at_multiplier, payout, created_at
`

type SettleBetParams struct {
	ID                    int64
	CashedOutAtMultiplier sql.NullInt32
	Payout                sql.NullInt64
}

func (q *Queries) SettleBet(ctx context.Context, arg SettleBetParams) (Bet, error) {
	row := q.db.QueryRowContext(ctx, settleBet, arg.ID, arg.CashedOutAtMultiplier, arg.Payout)
	var i Bet
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.PlayerID,
		&i.Amount,
		&i.AutoCashout,
		&i.CashedOutAtMultiplier,
		&i.Payout,
		&i.CreatedAt,
	)
	return i, err
}
