// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leaderboard.sql

package db

import (
	"context"
)

const getPlayerStanding = `-- name: GetPlayerStanding :one
SELECT rank, games, balance, total
FROM (
  SELECT
    p.id AS player_id,
    p.balance,
    COUNT(b.id)::bigint AS games,
    RANK() OVER (ORDER BY p.balance DESC, p.balance_updated_at ASC)::bigint AS rank,
    COUNT(*) OVER ()::bigint AS total
  FROM players p
  JOIN bets b ON b.player_id = p.id
  GROUP BY p.id, p.balance, p.balance_updated_at
) sub
WHERE player_id = $1
`

type GetPlayerStandingRow struct {
	Rank    int64
	Games   int64
	Balance int64
	Total   int64
}

func (q *Queries) GetPlayerStanding(ctx context.Context, playerID int64) (GetPlayerStandingRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayerStanding, playerID)
	var i GetPlayerStandingRow
	err := row.Scan(
		&i.Rank,
		&i.Games,
		&i.Balance,
		&i.Total,
	)
	return i, err
}

const listLeaderboard = `-- name: ListLeaderboard :many
SELECT display_name, hidden, balance, games, rank, player_id
FROM (
  SELECT
    p.id AS player_id,
    p.display_name,
    p.hidden,
    p.balance,
    COUNT(b.id)::bigint AS games,
    RANK() OVER (ORDER BY p.balance DESC, p.balance_updated_at ASC)::bigint AS rank
  FROM players p
  JOIN bets b ON b.player_id = p.id
  GROUP BY p.id, p.display_name, p.hidden, p.balance, p.balance_updated_at
) sub
ORDER BY rank
LIMIT $1 OFFSET $2
`

type ListLeaderboardParams struct {
	Limit  int32
	Offset int32
}

type ListLeaderboardRow struct {
	DisplayName string
	Hidden      bool
	Balance     int64
	Games       int64
	Rank        int64
	PlayerID    int64
}

func (q *Queries) ListLeaderboard(ctx context.Context, arg ListLeaderboardParams) ([]ListLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, listLeaderboard, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLeaderboardRow{}
	for rows.Next() {
		var i ListLeaderboardRow
		if err := rows.Scan(
			&i.DisplayName,
			&i.Hidden,
			&i.Balance,
			&i.Games,
			&i.Rank,
			&i.PlayerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
