// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Bet struct {
	ID                    int64
	RoundID               int64
	PlayerID              int64
	Amount                int64
	AutoCashout           sql.NullInt32
	CashedOutAtMultiplier sql.NullInt32
	Payout                sql.NullInt64
	CreatedAt             time.Time
}

type Player struct {
	ID                int64
	PubkeyFingerprint string
	DisplayName       string
	Balance           int64
	LastCreditDate    sql.NullTime
	CreatedAt         time.Time
	Hidden            bool
	BalanceUpdatedAt  time.Time
}

type Round struct {
	ID              int64
	CommitHash      string
	CrashMultiplier int32
	Salt            string
	State           string
	StartedAt       time.Time
	CrashedAt       sql.NullTime
	SettledAt       sql.NullTime
}
