// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package db

import (
	"context"
)

const adjustBalance = `-- name: AdjustBalance :one
UPDATE players
SET balance = balance + $2
WHERE id = $1
RETURNING id, pubkey_fingerprint, display_name, balance, last_credit_date, created_at
`

type AdjustBalanceParams struct {
	ID      int64
	Balance int64
}

func (q *Queries) AdjustBalance(ctx context.Context, arg AdjustBalanceParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, adjustBalance, arg.ID, arg.Balance)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.PubkeyFingerprint,
		&i.DisplayName,
		&i.Balance,
		&i.LastCreditDate,
		&i.CreatedAt,
	)
	return i, err
}

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (pubkey_fingerprint, display_name, balance)
VALUES ($1, $2, $3)
RETURNING id, pubkey_fingerprint, display_name, balance, last_credit_date, created_at
`

type CreatePlayerParams struct {
	PubkeyFingerprint string
	DisplayName       string
	Balance           int64
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, createPlayer, arg.PubkeyFingerprint, arg.DisplayName, arg.Balance)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.PubkeyFingerprint,
		&i.DisplayName,
		&i.Balance,
		&i.LastCreditDate,
		&i.CreatedAt,
	)
	return i, err
}

const getPlayerByFingerprint = `-- name: GetPlayerByFingerprint :one
SELECT id, pubkey_fingerprint, display_name, balance, last_credit_date, created_at FROM players WHERE pubkey_fingerprint = $1
`

func (q *Queries) GetPlayerByFingerprint(ctx context.Context, pubkeyFingerprint string) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByFingerprint, pubkeyFingerprint)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.PubkeyFingerprint,
		&i.DisplayName,
		&i.Balance,
		&i.LastCreditDate,
		&i.CreatedAt,
	)
	return i, err
}

const grantDailyCredit = `-- name: GrantDailyCredit :one
UPDATE players
SET balance = balance + $2,
    last_credit_date = CURRENT_DATE AT TIME ZONE 'UTC'
WHERE id = $1
  AND (last_credit_date IS NULL OR last_credit_date < CURRENT_DATE AT TIME ZONE 'UTC')
RETURNING id, pubkey_fingerprint, display_name, balance, last_credit_date, created_at
`

type GrantDailyCreditParams struct {
	ID      int64
	Balance int64
}

func (q *Queries) GrantDailyCredit(ctx context.Context, arg GrantDailyCreditParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, grantDailyCredit, arg.ID, arg.Balance)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.PubkeyFingerprint,
		&i.DisplayName,
		&i.Balance,
		&i.LastCreditDate,
		&i.CreatedAt,
	)
	return i, err
}

const updateDisplayName = `-- name: UpdateDisplayName :one
UPDATE players SET display_name = $1 WHERE id = $2 RETURNING id, pubkey_fingerprint, display_name, balance, last_credit_date, created_at
`

type UpdateDisplayNameParams struct {
	DisplayName string
	ID          int64
}

func (q *Queries) UpdateDisplayName(ctx context.Context, arg UpdateDisplayNameParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, updateDisplayName, arg.DisplayName, arg.ID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.PubkeyFingerprint,
		&i.DisplayName,
		&i.Balance,
		&i.LastCreditDate,
		&i.CreatedAt,
	)
	return i, err
}
