// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rounds.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createRound = `-- name: CreateRound :one
INSERT INTO rounds (commit_hash, crash_multiplier, salt, state)
VALUES ($1, $2, $3, 'betting')
RETURNING id, commit_hash, crash_multiplier, salt, state, started_at, crashed_at, settled_at
`

type CreateRoundParams struct {
	CommitHash      string
	CrashMultiplier int32
	Salt            string
}

func (q *Queries) CreateRound(ctx context.Context, arg CreateRoundParams) (Round, error) {
	row := q.db.QueryRowContext(ctx, createRound, arg.CommitHash, arg.CrashMultiplier, arg.Salt)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.CommitHash,
		&i.CrashMultiplier,
		&i.Salt,
		&i.State,
		&i.StartedAt,
		&i.CrashedAt,
		&i.SettledAt,
	)
	return i, err
}

const getRoundForVerification = `-- name: GetRoundForVerification :one
SELECT id, commit_hash, crash_multiplier, salt, state, started_at, crashed_at, settled_at
FROM rounds
WHERE id = $1
`

func (q *Queries) GetRoundForVerification(ctx context.Context, id int64) (Round, error) {
	row := q.db.QueryRowContext(ctx, getRoundForVerification, id)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.CommitHash,
		&i.CrashMultiplier,
		&i.Salt,
		&i.State,
		&i.StartedAt,
		&i.CrashedAt,
		&i.SettledAt,
	)
	return i, err
}

const listRecentRounds = `-- name: ListRecentRounds :many
SELECT id, commit_hash, crash_multiplier, salt, state, started_at, crashed_at, settled_at
FROM rounds
WHERE state IN ('crashed', 'settled')
ORDER BY id DESC
LIMIT $1
`

func (q *Queries) ListRecentRounds(ctx context.Context, limit int32) ([]Round, error) {
	rows, err := q.db.QueryContext(ctx, listRecentRounds, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Round{}
	for rows.Next() {
		var i Round
		if err := rows.Scan(
			&i.ID,
			&i.CommitHash,
			&i.CrashMultiplier,
			&i.Salt,
			&i.State,
			&i.StartedAt,
			&i.CrashedAt,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentRoundsWithStats = `-- name: ListRecentRoundsWithStats :many
SELECT
    r.id,
    r.commit_hash,
    r.crash_multiplier,
    r.salt,
    r.state,
    r.started_at,
    r.crashed_at,
    r.settled_at,
    COALESCE(SUM(b.amount), 0)::bigint  AS total_pot,
    COALESCE(SUM(b.payout), 0)::bigint  AS total_payout
FROM rounds r
LEFT JOIN bets b ON b.round_id = r.id
WHERE r.state IN ('crashed', 'settled')
GROUP BY r.id
ORDER BY r.id DESC
LIMIT $1
`

type ListRecentRoundsWithStatsRow struct {
	ID              int64
	CommitHash      string
	CrashMultiplier int32
	Salt            string
	State           string
	StartedAt       time.Time
	CrashedAt       sql.NullTime
	SettledAt       sql.NullTime
	TotalPot        int64
	TotalPayout     int64
}

func (q *Queries) ListRecentRoundsWithStats(ctx context.Context, limit int32) ([]ListRecentRoundsWithStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentRoundsWithStats, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentRoundsWithStatsRow{}
	for rows.Next() {
		var i ListRecentRoundsWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.CommitHash,
			&i.CrashMultiplier,
			&i.Salt,
			&i.State,
			&i.StartedAt,
			&i.CrashedAt,
			&i.SettledAt,
			&i.TotalPot,
			&i.TotalPayout,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revealOutcome = `-- name: RevealOutcome :one
UPDATE rounds
SET state = 'crashed',
    crashed_at = NOW()
WHERE id = $1
RETURNING id, commit_hash, crash_multiplier, salt, state, started_at, crashed_at, settled_at
`

func (q *Queries) RevealOutcome(ctx context.Context, id int64) (Round, error) {
	row := q.db.QueryRowContext(ctx, revealOutcome, id)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.CommitHash,
		&i.CrashMultiplier,
		&i.Salt,
		&i.State,
		&i.StartedAt,
		&i.CrashedAt,
		&i.SettledAt,
	)
	return i, err
}

const settleRound = `-- name: SettleRound :one
UPDATE rounds
SET state = 'settled',
    settled_at = NOW()
WHERE id = $1
RETURNING id, commit_hash, crash_multiplier, salt, state, started_at, crashed_at, settled_at
`

func (q *Queries) SettleRound(ctx context.Context, id int64) (Round, error) {
	row := q.db.QueryRowContext(ctx, settleRound, id)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.CommitHash,
		&i.CrashMultiplier,
		&i.Salt,
		&i.State,
		&i.StartedAt,
		&i.CrashedAt,
		&i.SettledAt,
	)
	return i, err
}

const updateRoundState = `-- name: UpdateRoundState :one
UPDATE rounds SET state = $2 WHERE id = $1 RETURNING id, commit_hash, crash_multiplier, salt, state, started_at, crashed_at, settled_at
`

type UpdateRoundStateParams struct {
	ID    int64
	State string
}

func (q *Queries) UpdateRoundState(ctx context.Context, arg UpdateRoundStateParams) (Round, error) {
	row := q.db.QueryRowContext(ctx, updateRoundState, arg.ID, arg.State)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.CommitHash,
		&i.CrashMultiplier,
		&i.Salt,
		&i.State,
		&i.StartedAt,
		&i.CrashedAt,
		&i.SettledAt,
	)
	return i, err
}
